Laravel 6 support
BKWLD/laravel-haml pull request #27
Opened 2019-09-24 14:52 UTC by petrenkorf

Fixed composer.json to accept Laravel 6 packages as dependencies.

2019-09-25 18:24 UTC, weotch requested changes
Small tweaks

2019-09-25 18:24 UTC, weotch commented on composer.json
> +    "name": "petrenkorf/laravel-haml",
```suggestion
    "name": "bkwld/laravel-haml",
```

2019-09-25 18:24 UTC, weotch commented on src/Bkwld/LaravelHaml/ServiceProvider.php
> +            case 6: $this->bootLaravel5(); break;
```suggestion
			case 6: $this->bootLaravel5(); break;
```

2020-12-26 02:54 UTC, dogaoz commented
It would be great if this could be merged so that we can use this on latest laravel 6 LTS.

2020-12-30 16:28 UTC, weotch commented on src/Bkwld/LaravelHaml/ServiceProvider.php
> +            6 => 'haml'
👍

2020-12-30 16:28 UTC, merged